<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Oil_level_glass.Presenters</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Oil level glass\Oil level glass.UI.Abstractions\Oil level glass.UI.Abstractions.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.csproj" />
    <ProjectReference Include="..\Oil level glass.UI.Abstractions\Oil level glass.UI.Abstractions.csproj" />
  </ItemGroup>

</Project>
