//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oil_level_glass.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oil_level_glass.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В поле «???» написан путь к несуществующей папке!.
        /// </summary>
        internal static string BadPathMessage {
            get {
                return ResourceManager.GetString("BadPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В поле «???» записано значение плотности, превышающее максимальное значение для данного материала!.
        /// </summary>
        internal static string BiggerMaxDensityMessage {
            get {
                return ResourceManager.GetString("BiggerMaxDensityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В поле «???» записано имя файла, превышающее 256 символов!.
        /// </summary>
        internal static string BigNameMessage {
            get {
                return ResourceManager.GetString("BigNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля «???» не должно превышать значения поля «!!!»!.
        /// </summary>
        internal static string BrokenHierarchyMessage {
            get {
                return ResourceManager.GetString("BrokenHierarchyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение поля «???» должно быть строго меньше значения поля «!!!»!.
        /// </summary>
        internal static string BrokenStrictHierarchyMessage {
            get {
                return ResourceManager.GetString("BrokenStrictHierarchyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chamferEdge {
            get {
                object obj = ResourceManager.GetObject("chamferEdge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap housingBlank {
            get {
                object obj = ResourceManager.GetObject("housingBlank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле «???» должно быть числом!.
        /// </summary>
        internal static string InvalidTypeMessage {
            get {
                return ResourceManager.GetString("InvalidTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В поле «???» записано значение плотности, меньшее минимального значения для данного материала!.
        /// </summary>
        internal static string LessMinDensityMessage {
            get {
                return ResourceManager.GetString("LessMinDensityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mainFormImage {
            get {
                object obj = ResourceManager.GetObject("mainFormImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mainFormImage1 {
            get {
                object obj = ResourceManager.GetObject("mainFormImage1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле «???» является обязательным для заполнения!.
        /// </summary>
        internal static string RequiredFieldMessage {
            get {
                return ResourceManager.GetString("RequiredFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap roundEdge {
            get {
                object obj = ResourceManager.GetObject("roundEdge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sharpEdge {
            get {
                object obj = ResourceManager.GetObject("sharpEdge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В поле «???» записано слишком большое значение!.
        /// </summary>
        internal static string TooBigFieldMessage {
            get {
                return ResourceManager.GetString("TooBigFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В поле «???» должно быть записано слишком маленьккое значение!.
        /// </summary>
        internal static string TooSmallFieldMessage {
            get {
                return ResourceManager.GetString("TooSmallFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле «???» должно содержать число больше нуля!.
        /// </summary>
        internal static string ZeroOrNegativeMessage {
            get {
                return ResourceManager.GetString("ZeroOrNegativeMessage", resourceCulture);
            }
        }
    }
}
