//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oil_level_glass.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oil_level_glass.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chamferEdge {
            get {
                object obj = ResourceManager.GetObject("chamferEdge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данной папки не существует!.
        /// </summary>
        internal static string DirectoryNotExistStrError {
            get {
                return ResourceManager.GetString("DirectoryNotExistStrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap housingBlank {
            get {
                object obj = ResourceManager.GetObject("housingBlank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mainFormImage {
            get {
                object obj = ResourceManager.GetObject("mainFormImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mainFormImage1 {
            get {
                object obj = ResourceManager.GetObject("mainFormImage1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ввод только чисел!.
        /// </summary>
        internal static string OnlyNumbersStrError {
            get {
                return ResourceManager.GetString("OnlyNumbersStrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ввод только чисел больше нуля!.
        /// </summary>
        internal static string OnlyPositiveNumbersStrError {
            get {
                return ResourceManager.GetString("OnlyPositiveNumbersStrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательное поле для заполнения!.
        /// </summary>
        internal static string RequiredStrError {
            get {
                return ResourceManager.GetString("RequiredStrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap roundEdge {
            get {
                object obj = ResourceManager.GetObject("roundEdge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sharpEdge {
            get {
                object obj = ResourceManager.GetObject("sharpEdge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком большое число!.
        /// </summary>
        internal static string TooBigNumberStrError {
            get {
                return ResourceManager.GetString("TooBigNumberStrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превышен лимит символов для данного поля!.
        /// </summary>
        internal static string TooManyCharsStrError {
            get {
                return ResourceManager.GetString("TooManyCharsStrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слишком маленькое число!.
        /// </summary>
        internal static string TooSmallNumberStrError {
            get {
                return ResourceManager.GetString("TooSmallNumberStrError", resourceCulture);
            }
        }
    }
}
