<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Oil_level_glass.ViewModels</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Core\Oil level glass.Core.csproj" />
    <ProjectReference Include="..\..\Model\Oil level glass.Model.csproj" />
  </ItemGroup>

</Project>
