<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Oil_level_glass.UI</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Editors\Glass\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\COM\Oil level glass.Core.COM.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.csproj" />
    <ProjectReference Include="..\Oil level glass.Presenters\Oil level glass.Presenters.csproj" />
    <ProjectReference Include="..\Oil level glass.UI.Abstractions\Oil level glass.UI.Abstractions.csproj" />
    <ProjectReference Include="..\Oil level glass.UI.Controls\Oil level glass.UI.Controls.csproj" />
  </ItemGroup>

</Project>
