<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Oil_level_glass.UI</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Editors\ModelProperties\KompasFiles\EditNamingForm.cs" />
    <Compile Remove="Editors\ModelProperties\KompasFiles\EditNamingForm.Designer.cs" />
    <Compile Remove="Editors\ModelProperties\View\ModelAppereanceForm.cs" />
    <Compile Remove="Editors\ModelProperties\View\ModelAppereanceForm.Designer.cs" />
    <Compile Remove="Editors\ModelProperties\View\ModelMaterialForm.cs" />
    <Compile Remove="Editors\ModelProperties\View\ModelMaterialForm.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Editors\ModelProperties\KompasFiles\EditNamingForm.resx" />
    <EmbeddedResource Remove="Editors\ModelProperties\View\ModelAppereanceForm.resx" />
    <EmbeddedResource Remove="Editors\ModelProperties\View\ModelMaterialForm.resx" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Editors\Glass\" />
    <Folder Include="Editors\ModelProperties\View\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\COM\Oil level glass.Core.COM.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.csproj" />
    <ProjectReference Include="..\Oil level glass.Presenters\Oil level glass.Presenters.csproj" />
    <ProjectReference Include="..\Oil level glass.UI.Abstractions\Oil level glass.UI.Abstractions.csproj" />
    <ProjectReference Include="..\Oil level glass.UI.Controls\Oil level glass.UI.Controls.csproj" />
    <ProjectReference Include="..\Oil level glass.UI.Utils\Oil level glass.UI.Utils.csproj" />
  </ItemGroup>

</Project>
